### ISSUE TITLE
ValidationForm immediate property is not work?

### ISSUE THREAD

**Issue by abakumov-v** [andyhu92/react-bootstrap4-form-validation#3]
On page https://andyhu92.github.io/react-bootstrap4-form-validation/#/api/validation-form if I check/uncheck property `immediate` then nothing happens.

Also I'm tryed set this property to true in my code - nothing happens also...

**Comment by andyhu92** [comment]
`immediate` means whether to validate the input `onChange` or `onBlur`, if set to `true`, then you should see the feedback message immediately as you typing, and if set to `false`, then the feedback message will be showed when you move away from current input. I tried and looks like it's working well for me, could you verify again?

**Comment by abakumov-v** [comment]
@andyhu92 I thought this property meant that the form would be validated immediately after rendering...

**Comment by andyhu92** [comment]
No...the form will only be validated when you submit it.
